[tool.poetry]
name = "aoc-2024"
version = "0.1.0"
description = ""
authors = ["Robin Schmidt contact@robinschmidt.dev"]

[tool.poetry.dependencies]
python = "^3.13"
advent-of-code-data = "^2.0.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
